Repository chunlohk/mywebclass-simulation, pull requests merged in 2023-03, with the labels that each got.

#1 Create docker image
  .github/workflows/publish.yml
Labels: enhancement

#12 Adding revised Privacy Policy into privacy.html
  src/privacy.html
Labels: documentation

#17 Pushing legal files
  CopyrightPolicy.md
  PrivacyPolicy.md
  ProductivityLog.md
Labels: documentation

#21 Modify main.js to display revised user consent
  src/js/main.js
Labels: documentation, enhancement

#23 Added SEO enhancements
  CNAME
  src/content.html
  src/index.html
  src/privacy.html
  src/story.html
  tests/robots.txt
Labels: enhancement

#22 Add language switcher to promote internalization in allPages.js
  src/index.html
  src/js/allPages.js
  src/js/language.js
Labels: documentation, enhancement

#29 Adding Data Processing Agreement Template as part of the Privacy Poli…
  src/content.html
Labels: documentation

#31 Update content page with Data Security Policy
  src/content.html
Labels: documentation, enhancement

#32 Add function to Disagree button
  src/js/main.js
Labels: documentation, enhancement

#33 Revise I diagree button function
  src/js/main.js
Labels: enhancement

#34 Update disagree button function
  src/js/main.js
Labels: enhancement

#35 Update I disagree button function
  src/js/main.js
  tests/privacy.disagree.spec.js
Labels: enhancement

#36 Correct I disagree function 3
  src/js/main.js
Labels: enhancement

#37 Create playwright to test modal agree button
  tests/PrivacyModalAgreeTest.js
Labels: enhancement

#38 Create playwright test for I disagree button in modal page
  tests/disagreeButtonTest.js
  tests/privacy.disagree.spec.js
Labels: documentation, enhancement

#39 Adding more playwright tests to test the links
  tests/developerEmailTest.js
  tests/privacyRedirectTest.js
Labels: documentation, enhancement

#43 Revise link to the get started button
  src/index.html
Labels: enhancement

#44 Revise link to the get started button 2
  src/index.html
Labels: enhancement

#45 added Google Analytics consent mode api fix attempt 1
  src/content.html
  src/getstarted.html
  src/index.html
  src/privacy.html
  src/story.html
Labels: enhancement

#48 Webclass
  src/content.html
  src/getstarted.html
  src/index.html
  src/privacy.html
  src/story.html
  tests/mywebclass_title.spec.js
Labels: bug

#47 reload old index to pass test
  src/index.html
Labels: bug

#54 adding cookie consent again in content page
  src/content.html
  src/getstarted.html
Labels: bug, enhancement

#58 Getstarted
  tests/getstartedbuttontest.js
Labels: documentation, enhancement

#59 Attempt to create a new contact page
  src/contact.html
Labels: enhancement

#62 Attempt to upload revised getstart page
  src/startnow.html
Labels: enhancement

#64 Adding images and contents into startnow page
  src/assets/images/Parents.jpg
  src/assets/images/Students.jpg
  src/assets/images/Teachers.jpg
  src/assets/images/teacher-group.jpg
  src/startnow.html
Labels: enhancement

#65 Try to make Get Started button
  src/index.html
Labels: enhancement

#66 Fix playwright tests syntax errors
  src/js/allPages.js
  src/js/language.js
  src/js/main.js
  tests/developerEmailTest.js
  tests/disagreeButtonTest.js
  tests/privacyRedirectTest.js
Labels: bug

#69 clean up extra image and fix other contents
  src/index.html
Labels: enhancement

#70 Revert changes on allPages.js and main.js
  src/js/allPages.js
  src/js/main.js
Labels: bug

#71 Fix Image Position
  src/index.html
Labels: bug

#72 Fix Image Position 2
  src/index.html
Labels: bug

#73 Update contact page
  src/contact.html
Labels: documentation

#74 Update Footer in contact page
  src/contact.html
Labels: enhancement

#75 Contact2
  src/contact.html
Labels: enhancement

#76 Update Privacy page format and contact us link
  src/privacy.html
Labels: enhancement

#78 testing something for google analytics
  src/index.html
Labels: enhancement

#80 Modify main.js to trigger google analysis
  src/js/main.js
Labels: enhancement

#83 Update PrivacyModalAgreeTest.js into test folder for future github ac…
  tests/PrivacyModalAgreeTest.js
Labels: documentation, enhancement

#84 Add ContactUsTitle.js into test folder for future github acton reference
  tests/ContactUsTitle.js
Labels: documentation, enhancement

#85 Update Privacy Information
  Team_Responsibility_Outline.md
  src/privacy.html
Labels: documentation

#86 Testing add homepage link in title
  src/privacy.html
Labels: enhancement

#87 Update broken links
  src/index.html
  src/privacy.html
Labels: enhancement

#88 Adding Accessibility test
  tests/accessiblility.spec.js
Labels: enhancement

#90 Fixing Chun's concerns
  tests/accessiblility.spec.js
Labels: enhancement

#112 finishing productivity log
  ProductivityLog.md
Labels: documentation

#117 attempt to automate npm run build results
  package-lock.json
  package.json
  update-webpack-result.js
  webpack-results.md
  webpack-stats.json
  webpack.config.js
  webpack.config.prod.js
Labels: documentation, enhancement

#118 User right content
  tests/UserRightContent.spec.js
Labels: documentation

#119 clear non working test
  tests/ContactUsTitle.js
  tests/PrivacyModalAgreeTest.js
  tests/developerEmailTest.js
  tests/disagreeButtonTest.js
  tests/getstartedbuttontest.js
  tests/privacyRedirectTest.js
Labels: documentation

#120 Create Privacy Modal Test in tests folder
  tests/PrivacyModalTest.spec.js
Labels: documentation

#121 Adding Loading Time Metric Tests
  package-lock.json
  package.json
  tests/websitemetrics.spec.js
Labels: documentation

#122 Adding Playwright Tests
  tests/AllClickableElementsTest.spec.js
  tests/NegativeTest.spec.js
  tests/NegativeTestForContact.spec.js
Labels: documentation

#123 Change index image to lower webpage size
  src/index.html
Labels: documentation

#125 Attempt to trim down index.js size 2
  package.json
Labels: bug

#126 Indexjswebpackfix
  package.json
  webpack.config.prod.js
Labels: bug
